version: '3.9'

services:
  gateway:
    build:
      dockerfile: ExamApp/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - GRPC_SERVICE_URL=http://domainservice:7014
    depends_on:
      - redis
      - domainservice
    deploy:
      resources:
        limits:
          cpus: "0.5"   # Ограничение использования CPU
          memory: 512M  # Ограничение памяти

  domainservice:
    build:
      dockerfile: DomainService/Dockerfile
    ports:
      - "7014:7014"
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 256M

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G

  mongo-compass:
    image: mongoclient/mongoclient:latest
    container_name: mongo-compass
    ports:
      - "3001:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - mongo
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 256M

  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:7.16.2
    container_name: logstash
    volumes:
      - ./elk/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
    depends_on:
      - opensearch
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1.5G

  opensearch:
    image: opensearchproject/opensearch:2.10.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
    ports:
      - "9200:9200"
      - "9300:9300"
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2G

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.10.0
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    depends_on:
      - opensearch
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

volumes:
  mongo_data:

networks:
  backend:
    driver: bridge
    external: true
